import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface InterviewData {
  overall_score: number;
  performance_label: string | null;
  role: string;
  skills: { name: string; score: number }[] | null;
  feedback: { title: string; text: string; type: string }[] | null;
}

export function generateInterviewPDF(data: InterviewData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const skills = data.skills || [];
  const feedback = data.feedback || [];

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Prepzo - Performance Report", pageWidth / 2, 20, { align: "center" });

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(`Overall Score: ${data.overall_score}/100 — ${data.performance_label ?? "N/A"}`, pageWidth / 2, 35, { align: "center" });

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Skill Breakdown", 14, 50);

  autoTable(doc, {
    startY: 55,
    head: [["Skill", "Score"]],
    body: skills.map((s) => [s.name, `${s.score}%`]),
    theme: "striped",
    headStyles: { fillColor: [99, 102, 241] },
  });

  const feedbackY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("AI Feedback & Suggestions", 14, feedbackY);

  autoTable(doc, {
    startY: feedbackY + 5,
    head: [["Type", "Title", "Details"]],
    body: feedback.map((f) => [
      f.type === "strength" ? "✅ Strength" : "💡 Improvement",
      f.title,
      f.text,
    ]),
    theme: "striped",
    headStyles: { fillColor: [99, 102, 241] },
    columnStyles: { 2: { cellWidth: 80 } },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(10);
  doc.setFont("helvetica", "italic");
  doc.text(`Generated by Prepzo on ${new Date().toLocaleDateString()}`, pageWidth / 2, finalY, { align: "center" });

  doc.save("Prepzo-Report.pdf");
}
